### ISSUE TITLE
编译错误iOS

### ISSUE THREAD

**Issue by tormentous** [trojan-gfw/igniter-go-libs#6]
...
In file included from /var/folders/p3/s_s0szld2k90_vkbkxqm5vjc0000gn/T/gomobile-work-152939460/pkg/mod/github.com/trojan-gfw/go-tun2socks@v1.16.3-0.20200303012513-67fe855da98a/core/c/custom/arch/cc.h:5:
/var/folders/p3/s_s0szld2k90_vkbkxqm5vjc0000gn/T/gomobile-work-152939460/pkg/mod/github.com/trojan-gfw/go-tun2socks@v1.16.3-0.20200303012513-67fe855da98a/core/c/custom/arch/cc_android.h:12:10: fatal error: 'android/log.h' file not found
#include <android/log.h>
         ^~~~~~~~~~~~~~~
1 error generated.

make: *** [ios] Error 1

**Comment by wongsyrone** [comment]
Sorry, the library is intended to be used by igniter, no plan for iOS.

**Comment by tormentous** [comment]
OK 可能删除iOS的“ Log” 最近编译
